### ISSUE TITLE
Duplicating Cells in Swift

### ISSUE THREAD

**Issue by WillemPieterse** [Augustyniak/RATreeView#101]
Hi there, 
I am using RATreeview, and I love it! 

However, when you expand a section for the second time the children duplicate, a third time and the repeat three times etc etc. 

I stepped through my code and noticed "number of Children" and "Child of Item " returns the correct values. "Cell for Item" is called repeatedly and causes the unwanted repeats. Below my code for your perusal.

-------------------

import UIKit

class WoundCareViewController: UIViewController,RATreeViewDataSource,RATreeViewDelegate {

      var table = RATreeView()
    var _categories : RLMResults
   
    
    @IBOutlet weak var tableView: UIView!
    required init(coder aDecoder: NSCoder)
    {
        _categories = WoundDressingTypeLocal.allObjects()
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()

        
        let frame = tableView.frame
        tableView.removeFromSuperview()
        
        table.frame = frame
        table.delegate = self
        table.dataSource = self
        var typeCell = UINib(nibName: "WoundDressingTypeTableViewCell", bundle:nil)
        table.registerNib( typeCell, forCellReuseIdentifier: "dressingTypeCell")
        
        var dressingCell = UINib(nibName: "WoundDressingTableViewCell", bundle:nil)
        table.registerNib( dressingCell, forCellReuseIdentifier: "dressingCell")
        
        self.view.addSubview(table)
        table.reloadData()

        
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func treeView(treeView: RATreeView!, numberOfChildrenOfItem item: AnyObject!) -> Int {
        var i = 0
        if item == nil{
            i = Int( _categories.count)
        } else if item is WoundDressingTypeLocal{
            let type = item as WoundDressingTypeLocal
            let res = WoundDressingLocal.allObjects().objectsWhere("WoundDressingType = '\(type.descr)'")
            i = Int(res.count)
        }
        return i
    }
    
    func treeView(treeView: RATreeView!, child index: Int, ofItem item: AnyObject!) -> AnyObject! {
        var childToReturn : AnyObject = NSObject()
        if item == nil{
            let b = _categories[UInt(index)] as WoundDressingTypeLocal
            childToReturn = b
        }else if item is WoundDressingTypeLocal{
            let type = item as WoundDressingTypeLocal
            let res = WoundDressingLocal.objectsWhere("WoundDressingType = '\(type.descr)'")
            let s = res[UInt(index)] as WoundDressingLocal
            childToReturn = s
        }
        return childToReturn
    }
    
    func treeView(treeView: RATreeView!, cellForItem item: AnyObject!) -> UITableViewCell! {
        var cell = UITableViewCell()
        
        var level = treeView.levelForCellForItem(item)
        println(item)
        if level == 0{
            let dressingTypeCell = treeView.dequeueReusableCellWithIdentifier("dressingTypeCell") as WoundDressingTypeTableViewCell
            dressingTypeCell.dressingTypeDescr.text = "\((item as WoundDressingTypeLocal).descr)"
            //chpCell.chapterDescription.text = (item as ChapterLocal).descr
            cell = dressingTypeCell
        }else if level == 1{
            let dressingCell = treeView.dequeueReusableCellWithIdentifier("dressingCell") as WoundDressingTableViewCell
            dressingCell.dressingDescription.text = "\((item as WoundDressingLocal).descr)"
            //chpCell.chapterDescription.text = (item as ChapterLocal).descr
            cell = dressingCell
            
        }
        return cell
    }

**Comment by Augustyniak** [comment]
@WillemPieterse I pushed new version of the library which should fix some of the problems with expanding operations. Can you verify whether this issue still exist in version 1.0.2 ?

**Comment by WillemPieterse** [comment]
Thank you so much. Will defenitely let you know... I like RATreeview alot!

On Wed, May 6, 2015 at 10:51 AM, Rafał Augustyniak <notifications@github.com

**Comment by Augustyniak** [comment]
Note: Version `1.0.3` has been released. It fixes some of the problems, related to duplicated cells, that were not fixed in version `1.0.2`.

Closing. Feel free to reopen if necessary.
