### ISSUE TITLE
selectRowForItem:animated:scrollPosition: bug

### ISSUE THREAD

**Issue by Arrnas** [Augustyniak/RATreeView#103]
with a tree structure such as:
base1
----item1
----item2
----item3
----item4
base2
base3
base4
base5

when calling selectRowForItem:item1..., selectRowForItem:item2..., selectRowForItem:item3..., selectRowForItem:item4... the method will select rows 1,2,3,4 with item1,item2,item3,item4 correctly but if base1 is collapsed it will still select the same index paths but now the selected rows have base2,base3,base4,base5.

**Comment by Arrnas** [comment]
made a quick fix, haven't tested it much but it seems to work

**Comment by Augustyniak** [comment]
@Arrnas Thanks! I will take a look within a few days.

**Comment by Augustyniak** [comment]
Version 1.0.2 contains the fix. Thanks @Arrnas !
