### ISSUE TITLE
The bug in recursive expand operation is yet to fixed in RATreeView 1.0.1

### ISSUE THREAD

**Issue by kkk669** [Augustyniak/RATreeView#104]
Hi,

The old version of RATreeNodeCollectionController.m has been bundled into RATreeView 1.0.1 archives.

**Comment by Fogh** [comment]
I have tried applying the fix from #a165012, it still doesn't fix the bug.

**Comment by Augustyniak** [comment]
@kkk669 Version 1.0.2 contains your fix.
