### ISSUE TITLE
A bug problem about - (void)expandRowForItem:(id)item

### ISSUE THREAD

**Issue by gtgg** [Augustyniak/RATreeView#105]
When I call this function “- (void)expandRowForItem:(id)item”， the cell number doubled。 The old cell still retained。 But in v0.9.2 is OK @Augustyniak

**Comment by Fogh** [comment]
Yes, it seems like you get double cells when expanding a parent.

**Comment by Augustyniak** [comment]
Sorry for the long response time. I will try to post an update this week which fixes mentioned problem. I will post a comment here once new version is released.

**Comment by Fogh** [comment]
I just created a pull request. Added a exclamation mark, which fixes the problem for me.

**Comment by Augustyniak** [comment]
Fixed in a51d882e9925e637b6cedc9b013a844aeb7c3b5e.
