### ISSUE TITLE
treeView childOfItem requests children at out of range indices

### ISSUE THREAD

**Issue by heyalexchoi** [Augustyniak/RATreeView#106]
Problem occurs primarily when trying to expand cells. 

I believe I am implementing datasource methods correctly:

```
func treeView(treeView: RATreeView!, numberOfChildrenOfItem item: AnyObject!) -> Int {
        if item == nil {
            return wrappedComments.count
        } else if let wrappedComment = item as? CommentWrapper {
            return wrappedComment.children.count
        }
        
        println("this isnt supposed to happen. item: \(item)")
        return 0
    }
```

```
func treeView(treeView: RATreeView!, child index: Int, ofItem item: AnyObject!) -> AnyObject! {
        if item == nil {
            return wrappedComments[index]
        } else if let wrappedComment = item as? CommentWrapper {
            return wrappedComment.children[index]
        }
        println("this isnt supposed to happen. item: \(item)")
        return nil
    }
```

![screen shot 2015-04-26 at 12 22 21 am](https://cloud.githubusercontent.com/assets/4961047/7335881/593d1ed8-ebaa-11e4-8627-bf3a886dc42e.png)

**Comment by Augustyniak** [comment]
Hey,

Thanks for the report. Sorry for the *really* long response time. Your code looks ok. Are you experiencing described issues in the newest release of the *RATreeView*? Were you able to somehow solve your issues?

**Comment by Augustyniak** [comment]
Note that `RATreeView` [2.1.0](https://github.com/Augustyniak/RATreeView/releases/tag/v2.1.0) provides improvement experience when working with Swift.

I hope that it helps. Closing. Feel free to reopen if necessary.
