### ISSUE TITLE
How to expand tree to a specific node?

### ISSUE THREAD

**Issue by abbasmousavi** [Augustyniak/RATreeView#109]
How can I expand tree to a specific node, for example a > b > c programmatically? Should I call expand expandRowForItem: on a, b and c in a loop? Where is the appropriate point for doing this so that user can see the "c" node when view appears?

I tried this in viewDidLoad after reloadData and also in ViewDidAppear, I also tried expandRowForItem:expandChildren:withRowAnimation: with RATreeViewRowAnimationNone without success

for (item in [a, b, c]) {
            [self.treeView expandRowForItem:item];
 }

**Comment by Augustyniak** [comment]
Yes, currently you have to call expanding of the a > b > c programmatically.

**Comment by abbasmousavi** [comment]
As I said in previous post, this method does not work in viewDidLoad or viewDidApear after reload data. Where should I do this?

**Comment by danielrak** [comment]
Also having trouble with this. Maybe we can figure this out together. Any ideas?

**Comment by abbasmousavi** [comment]
@Augustyniak, Can you please help us with some explanation or sample code?

**Comment by Augustyniak** [comment]
@abbasmousavi I will investigate this problem and post an answer tomorrow at the end of the day.

**Comment by Augustyniak** [comment]
@abbasmousavi I tried to replicate the issue but everything seems to work for me.
 I added two lines at the end of the `viewDidLoad` method in RAViewController` (pasting them below) and `RATreeView` behaves correctly.

    [self.treeView expandRowForItem:self.data[1]];
    [self.treeView expandRowForItem:[self.data[1] children][0]];

One more question: Are you using batch updates?

**Comment by abbasmousavi** [comment]
@Augustyniak, no, I don't use batch updates but with 1.0.3 expansion works correct in the end of viewDidLoad. Thanks.

**Comment by Augustyniak** [comment]
Great to hear that :smile:.

Closing. Feel free to reopen if necessary.
