### ISSUE TITLE
Please help . How to insert an item in tree view the last line.

### ISSUE THREAD

**Issue by LvJianfeng** [Augustyniak/RATreeView#114]
i need to insert an item the last line,but do not reloadData with tree.

**Comment by Augustyniak** [comment]
Hey,
What about using `- (void)insertItemsAtIndexes:(NSIndexSet *)indexes inParent:(id)parent withAnimation:(RATreeViewRowAnimation)animation;` method (with correct arguments)?

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.

**Comment by LvJianfeng** [comment]
Problem has been solved with thanks.
