### ISSUE TITLE
insert new item as root

### ISSUE THREAD

**Issue by sarn** [Augustyniak/RATreeView#117]
Is it possible to insert a new item on the root level? 

I found the `- (void)insertItemsAtIndexes:(NSIndexSet *)indexes inParent:(id)parent withAnimation:(RATreeViewRowAnimation)animation` method. This method works nicely if the parent is not nil. But there is a crash if you want to insert an item without the parent on the root level.

Funny is that you can delete an item on the root level without any problems at all. Do I miss something or is this not supported? What would be needed to support it, if it is not? Any code insights?

**Comment by outoftrun** [comment]
You might need to actually change the root of the data, I subclass RATree to contain the data root, also look at the Rebuild command I am rebuild when I change the root, but I not entirely sure it is necessary.

**Comment by sarn** [comment]
Hmm I think this should work with some simple changes on the RATreeView code. 

For more details: the crash is happening in the `insertChildControllers:(NSArray *)controllers atIndexes:(NSIndexSet *)indexes` method. The code tries to insert objects on the line `[self.mutablechildControllers insertObjects:controllers atIndexes:indexes]` which fails with the following exception `'NSInvalidArgumentException', reason: '*** -[NSMutableArray insertObjects:atIndexes:]: count of array (0) differs from count of index set (1)'`

Any insight why this is happening?

**Comment by sarn** [comment]
I also see, that if I try to add some item to the root, a `RATreeNodeController` is reused and copied from `oldControllerForCurrentIndex` instead of a new one. Could that be the issue? What are `lazyItem`s for, which probably trigger this behavior?

**Comment by sarn** [comment]
OK for anyone who struggles with the same issue. If you want to insert a new row on the root level, you need to change the underlying data as well (the `data` array). E.g. add a new `RADataObject` to the `data` array and then call the `insertItemsAtIndexes:` with `nil` for the `inParent:` argument.
