### ISSUE TITLE
How do you change the bg color 

### ISSUE THREAD

**Issue by Hacoga** [Augustyniak/RATreeView#120]
Hello, first thank so much for this controller.

I have a dude, can I change the background color of cells of level 1?

Greetings from México!

**Comment by Augustyniak** [comment]
Hey, 
There is no explicit support for that in RATreeView. You can check how it is done in an example project by looking into implementation of `treeView:cellForItem:`.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
