### ISSUE TITLE
How can I get all child nodes

### ISSUE THREAD

**Issue by arnoldschmid** [Augustyniak/RATreeView#121]
Hi,
first of all compliments for RATreeView. I' m trying to work with it using swift(I am newbie). I am able to get the parent of a node, but I didn't find a function to get all child nodes. I created parents with a button (checkbox). After a click on the button in the parent field, I would like to change the buttons in the child nodes. 
I tried to use another way, but I don't understand why the function 
func treeView(treeView: RATreeView!, didSelectRowForItem item: AnyObject!) { ...}
will only be called if I click on the label of the custom cell (xib-File). I have also a Checkbox (Button), but if I click on them the didSelectRowForItem will not be called.

thank you
Arnold

**Comment by Augustyniak** [comment]
Hey,

Method ` treeView(treeView: RATreeView!, didSelectRowForItem item: AnyObject!)` is called only when you don't expend the cell from the code. You probably (correct me if I'm wrong) do that from code in case you use Checkbox (button).

You can get child nodes in different way. As you have access to the data source of your `RATreeView` you can get child models of the model that is represented by the cell you want to expend. Next, you can get cells for that child models by calling `cellForItem:` for each of them.

I hope this answers your questions.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
