### ISSUE TITLE
Issue with background color

### ISSUE THREAD

**Issue by flaviobittenca** [Augustyniak/RATreeView#124]
Hey there!

Since I'm testing RATreeView in some apps in the iOS 9 environment, I'm not able to change the color of the background of the TableView. White color appears and I can't change it.
I don't have this issue with iOS < 9.

Hope you can solve it or give me a hint about it. Thanks!

**Comment by Augustyniak** [comment]
Hey,
Thanks for the report. I haven't had time to test `RATreeView` using iOS9 yet.
Have you fixed the issue with the white background?

**Comment by flaviobittenca** [comment]
Hey! 

So, I have "fixed" the issue. 
I don't know why, I was using a previous version (< 0.9) of the RATreeView, that didn't support embeddedTableView as property. I just updated the library in my project, and now it's working normally!

Thanks for your attention!

**Comment by flaviobittenca** [comment]
Hey!

So, I have "fixed" the issue. 
I found a fork (https://github.com/jhays/RATreeView) that fixed exactly this problem. Apparently is needed to support embeddedTableView as property. I just updated this point in my project, and now it's working normally!

**Comment by Ageleswari** [comment]
Hi,
I've cloned the fixed fork and checked but my app still has the white background for the tableView in iOS9. Will you be able to fix it or provide any suggestion to fix it? 
hope to hear from you soon.
Thank you.

**Comment by vivekshah05** [comment]
Hello,
I am facing the same issue, White background for the tableview in iOS 9.
Can any one help me ?

**Comment by Ageleswari** [comment]
[[UIScrollView appearance] setBackgroundColor:[UIColor clearColor]]; 
will solve it.

**Comment by vivekshah05** [comment]
Thanks @Ageleswari  You saved my time.

**Comment by Augustyniak** [comment]
Problem with the background color of the underlying *scroll view* was fixed in #151. Refer to description of the #151 and #129 for more details.
