### ISSUE TITLE
How do I find the height of the tree after I expand a node? 

### ISSUE THREAD

**Issue by DanielRakh** [Augustyniak/RATreeView#125]
I found that when a cell is not expanded the height == treeView.contentSize. 

However, when I expand a cell the contentSize seems to return a different value than what SHOULD be currentHeight + height of expanded cell. 

How can I obtain the height of the Tree View once it's expanded? 

My context is that I have the Tree View as a subview of a cell of a generic table view and I need to expand the cell accordingly to fit the tree view as it expands. I'm currently doing that by setting a height constraint on the tree view equal to the content size of the tree view and using that height constraint to auto layout the cell that contains that tree view but it breaks down when I get the wrong contentSize of the tree as I expand a cell. 

Any ideas? Am I implementing something wrong?

**Comment by Augustyniak** [comment]
Hey,

Thanks to your report I found a bug/issue in the current implementation. Mentioned by you problems should be fixed in https://github.com/Augustyniak/RATreeView/commit/e52923186a78abc2b1496843dc718fbd702f4a8c.

I hope that this helps. 
Closing. Feel free to reopen if necessary.
