### ISSUE TITLE
Add spacing between cells

### ISSUE THREAD

**Issue by chlebta** [Augustyniak/RATreeView#126]
Hello, How to add spacing between cells, like when using tableview with section instead of rows :
http://i.stack.imgur.com/MPsuR.png

**Comment by DanielRakh** [comment]
Technically you can't. You need to use a collection view for that. But you can make it seem like theres spacing. You need to add another subview to the content view of each cell where the height of the subview is say 10 points less than the height of the content view. Then set the backgroundColor of the contentView and cell to clearColor. This gives the illusion of spacing.

**Comment by Augustyniak** [comment]
@DanielRakh is right. You can achieve this manually by using transparent views/cells.
Closing. Feel free to reopen if necessary.
