### ISSUE TITLE
Collapse all SubCells when it's root cell got collapse.

### ISSUE THREAD

**Issue by vivekshah05** [Augustyniak/RATreeView#128]
Hello,
When I expand Computers ,it shows computer1 and when expanding computer1 it shows notebook1.
Then collapsing computers and again expanding computer it expand as it's previous stage.
I want to collapse all the subcells. How can I do this?
Please help me.

**Comment by Augustyniak** [comment]
Hi, 
You have to set `collapsesChildRowsWhenRowCollapses` property of the `RATreeView` to `YES`

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
