### ISSUE TITLE
Can't disable animation?

### ISSUE THREAD

**Issue by rdougan** [Augustyniak/RATreeView#133]
I've tried setting `rowsExpandingAnimation` and `rowsCollapsingAnimation` to `RATreeViewRowAnimationNone` but it does not seem to make a difference.

Looking at the code, no matter what I do, even when using `UITableViewRowAnimationNone` - it still animates.

I noticed some CATransaction stuff in `collapseCellForTreeNode:informDelegate:` - but removing that also did nothing.

I'm stumped. I've no idea how the animation is actually being performed. What am I missing?

**Comment by ninjaprox** [comment]
@rdougan: It's behaving correctly. You can try this by inserting/deleting rows in a normal `UITableView` with `UITableViewRowAnimationNone`. `RATreeView` has an `UITableView` inside to lift heavy job in row insertion and deletion. In addition, `RATreeViewRowAnimationNone` is just another name of `UITableViewRowAnimationNone` used in `RATreeView` so it doesn't affect the animation at all ([see here](https://github.com/Augustyniak/RATreeView/blob/afd20ab638a979c65bed589518445a038976a7f0/RATreeView/Private%20Files/RATreeView%2BEnums.m#L28)).

**Comment by rdougan** [comment]
Oh man, I feel so dumb. Thank you!

I disabled the animations by using `[UIView setAnimationsEnabled:NO];`.
