### ISSUE TITLE
Change SubCell's data runtime

### ISSUE THREAD

**Issue by vivekshah05** [Augustyniak/RATreeView#134]
Hello,
I have requirement in which I have to replace subcell data with other data on runtime.
So how can I change my subcell data on click of button runtime.
Please help me.

**Comment by Augustyniak** [comment]
If I correctly understands you needs, you probably should use `reloadRowsForItems:withRowAnimation:` method.

**Comment by Augustyniak** [comment]
Closing this issue. Feel free to reopen if necessary.
