### ISSUE TITLE
Unable to expand the view when loading as sub controller 

### ISSUE THREAD

**Issue by guptaankit2190** [Augustyniak/RATreeView#136]
Please help i'm unable to figure out why i'm not able to expand the cell when using the ViewController containing tree view as sub controller of some other controller.

When calling the following method explicitly child cell get displayed but indentation of the cell does not set correctly.
expandRowForItem: expandChildren: withRowAnimation:

**Comment by Augustyniak** [comment]
Hey,

How do you modify/set indentation of the cells in your project/application? Note that indentation isn't set in the cells by the `RATreeView` itself. You have to do it manually. You can find how you can achieve that by checking example project - piece of code available at https://github.com/Augustyniak/RATreeView/blob/master/Demo/RATableViewCell.m#L52-L79 should be especially interesting for you.

**Comment by guptaankit2190** [comment]
Thanks for your help, i was facing last issue because i have set margin from the top of the view. When i have changed it to default it started working. I didn't understand this why it happened. 

I have set indentation explicitly but it doesn't get updated when i expand row for the first time, when re-expand it again it shows correctly. Can you help me out of this??

Thanks Regards

**Comment by Augustyniak** [comment]
@guptaankit2190 Can you provide me the code responsible for setting indentation in your project? It would help me to help you. :smile:

**Comment by guptaankit2190** [comment]
Hi, 
I have used your code and tweaked as per my need and it works great thanks for the help. 


Saturday, 28 November 2015, 7:57 PM +0530 from Rafał Augustyniak  <notifications@github.com>:

**Comment by Augustyniak** [comment]
Great to hear that :smile: . Closing. Feel free to reopen if necessary.
