### ISSUE TITLE
Re-Order rows via Reorder control feature

### ISSUE THREAD

**Issue by clintinthecode** [Augustyniak/RATreeView#146]
Hi,

I created issue 87 a while ago, i have a new github account so i cant reopen it. https://github.com/Augustyniak/RATreeView/issues/87

The feature request was for reordering rows using the reorder row icon on each cell.

I cant see how this can be done using the existing code, and I cant find any way to use the existing moveItem method to make this happen.

**Comment by Augustyniak** [comment]
Sorry for closing #87 without providing you with a satisfactory answer.

I added additional comment in #87 and reopened this issue so you can comment there if you want.

Closing this ticket. Please reopen if necessary.
