### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by shenguanjiejie** [Augustyniak/RATreeView#149]
@property (copy, nonatomic) UIVisualEffect *separatorEffect NS_AVAILABLE_IOS(8_0) UI_APPEARANCE_SELECTOR __TVOS_PROHIBITED;

This row is error...please fix it! thanks

**Comment by Augustyniak** [comment]
Hey,

Fixed in 8598604576a459c8c5b43db6d8d082a9371f22a2.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.

**Comment by shenguanjiejie** [comment]
Thank you very much!
and best wishes for you  : )
