### ISSUE TITLE
Question: How can I use RATreeView with a storyboard?

### ISSUE THREAD

**Issue by kmav** [Augustyniak/RATreeView#160]
Is there any way to integrate with storyboards? For example, if there was some integration with tableviewcontroller then we could create segues more easy.

**Comment by joshjack** [comment]
Just like the examples, you need a class that implements UIViewController.  In storyboard you can create a blank UIViewController instance.  You can add toolbars, etc; and set up your segues.  In the class implementation, manually add your RATreeview as a subview in ViewDidLoad (just like the example).

**Comment by kmav** [comment]
Thank you for your reply :)

I have already integrated with simple view controller storyboard object following the example. But, I think that the example is more focused on a programming solution.
1. When you touch a row, the children of the node unfolds. What I would prefer is to find out how I can create a segue/link to a next view controller to see details for the specific node. I think that the functionality to unfold on touch of a row is somehow buildin. Please correct me...
2. Can I use a tableviewcontroller storyboard object instead of simple view controller and how the programmatic functionality of RATreeView can be integrated with TableViewController cells etc.?

**Comment by AndrewSB** [comment]
@kmav I don't think you can really use `RATreeView` as you'd like with storyboards, because it doesn't subclass UITableView, but UIView.
So you need to take you UIView reference and then set everything up programmatically in `viewDidLoad`. Found a (much less popular) [alternative library](https://github.com/varun-naharia/UITreeView) that subclasses UITableView, going to give using it a shot instead.

**Comment by kmav** [comment]
@AndrewSB Thank you for your feedback and the information for alternative library. In RATreeView library there is an RATableView class that inherits from UITableView. I wonder if I can use that to establish the integration.
Also, regarding segues, i.e. opening a detail view when the user touches on a tree row, what I have noticed is that when you touch a tree row the children of that row are expanding/unfold. Can I change the functionality of touching a row to e.g. open a detail view and use some other control for expanding the children, or is this not permitted at all (this is how it is designed)?

**Comment by joshjack** [comment]
I apologize for missing your response to my initial comment.

When using a navigation controller you must use the "embed in" command in storyboard for any child view controllers to automatically add the toolbar and prevent overlap over sub views.

Regarding the expand/collapse functionality - implement the "should expand cell" and "should collapse cell" delegate methods to always return No. That will turn off the automatic expand/collapse action.

In my programs I use an addition style button that is only displayed by cells with children.  Tapping that button calls "expand" or "collapse" on the cell, and reloads the tree view.

capture the tapping action like a normal tableview cell with "didselect"


Joshua Jackson, PhD
Senior Research Engineer
 (800) 604-1822 
   (256) 648-5109
 josh@nside.io   www.nSide.io
 4031 Parkway Dr, Suite B, Florence, AL 35630

**Comment by AndrewSB** [comment]
@kmav I don't think it's possible to use the private internal class to make a table. I ended up just rolling my own solution for this, since I only needed one level of collapsibility it wasn't too bad.

Can share my solution if it would be of any help with you

**Comment by kmav** [comment]
@joshjack and @AndrewSB thank you so much for your kind assistance and explanations that show me the direction to follow.
I will experiment a while and get back to you.

**Comment by kmav** [comment]
@joshjack 
After inactivating default shouldExpand/Collapse, what do you call to reproduce their behaviour with the '+' style button?

**Comment by joshjack** [comment]
@kmav it's a tree view command, something like [_mytreeview expandrowforcell:cell];

Because this is done as a code block using weak self inside the cell creation method (just like the demos), you have access to both the cell and the parent tree view.

**Comment by kmav** [comment]
@joshjack I have implemented most of what you suggested related to collapse/expand with an addition symbol and it works!
performseguewithidentifier crashes, because, I think, as @AndrewSB pointed out, RATreeView cannot be used as a UITableView, so I cannot create in storyboards a TableView object and connect it to my RATreeView. So, I cannot have a cell view to start ctrl-drag from it to my next detail scene.

What I did for the moment, is a programmatic solution in didSelectRowForItem as below.
```objective-c
- (void)treeView:(RATreeView *)treeView didSelectRowForItem:(id)item {
    
    TeamTableViewController *detailViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"UnitTeam"];
    if (detailViewController) {
        detailViewController.activeUser = self.activeUser;
        OrgUnitsChildren *dataObject = [self.treeView itemForSelectedRow];
        NSLog(@"... with unitID %d", (int)dataObject.unitID);
        [detailViewController setActiveUnit:[[Unit alloc] initWithName:dataObject.name unitID:[NSString stringWithFormat:@"%f",dataObject.unitID] lat:[NSString stringWithFormat:@"%f",dataObject.latitude] lng:[NSString stringWithFormat:@"%f",dataObject.longitude]]];
    }
    [self.navigationController pushViewController: detailViewController animated:YES];
     
}
```

**Comment by joshjack** [comment]
@kmav here's an alternate approach:
#1 - create a segue in storyboard that is connected not from a cell, but from the parent viewcontroller of the RATreeView.  This is done by CTRL-CLICK dragging from the viewcontroller icon (yellow icon) at the top of the canvas to the next view.  You will be prompted to choose what type of seque to use.
#2 - name the segue like, "segueToTeamTBVC"
#3 -  
```
- (void)treeView:(RATreeView *)treeView didSelectRowForItem:(id)item {
            [self performSegueWithIdentifier:@"segueToTeamTBVC" sender:self];    
}
```

You'll still have to pass the "activeUser" somehow (I use a singleton class for that).

*Last note - this line:
`OrgUnitsChildren *dataObject = [self.treeView itemForSelectedRow];`
should be simplified to:
`OrgUnitsChildren *dataObject = item;`

**Comment by kmav** [comment]
@joshjack 
Yes. You have right! I failed yesterday with that ctrl-click just due to bad arrangement of my scenes!!! 
Thank you very much for your help.
