### ISSUE TITLE
Is it possible to bind the row selection event to additional button action

### ISSUE THREAD

**Issue by Ram569** [Augustyniak/RATreeView#166]
I don't want to expand the tree on selecting row, instead will add one more button for each row, on clicking the button we will show the child nodes. Is it possible to bind the table row selection event to the additional button action.

**Comment by joshjack** [comment]
Yes. Handle the shouldexpandrow and shouldcollapserow delegates and return NO. This will disabled the automatic expanding and collapsing during selection.

In the cell for Item method, implement the button delegate using a weak self like the example code. Call expandrowforitem or collapserowforitem based on current status. 


Joshua Jackson, PhD
Senior Research Engineer
 (800) 604-1822 
   (256) 648-5109
 josh@nside.io   www.nSide.io
 4031 Parkway Dr, Suite B, Florence, AL 35630

**Comment by Ram569** [comment]
Thanks @joshjack , It works :+1: ) .
