### ISSUE TITLE
How to set first row expanded by default?

### ISSUE THREAD

**Issue by AnujAroshA** [Augustyniak/RATreeView#179]
How can I set first row expanded when the view is loading?

I was able to identify the first row and tried below code line to set it expanded

`[_treeView expandRowForItem:item];`

Actually it expands the first row. But it keep opening even I try to close it. I have implemented a mechanism to close already expanded row like below inside willExpandRowForItem method

`[_treeView collapseRowForItem:alreadyExpandedItem];`

**Comment by PoissonBallon** [comment]
Hi @AnujAroshA did you success to expand the first cell ?

**Comment by Augustyniak** [comment]
Hi, 

Actually you're right @AnujAroshA, `_treeView expandRowForItem:item` should work. 👍 The important part is the place when you put that code. Aforementioned expansion should happen just after tree view loads its data - probably in `viewDidLoad` or `viewWillAppear`.

I'm closing this issue for now - feel free to reopen if necessary.

**Comment by zhouhao27** [comment]
It doesn't work for me. In my viewDidAppear:

```
    data = loadData()
    data.forEach { item in
      treeView.expandRow(forItem: item)
    }
    treeView.reloadData()
```

But all the rows are not expanded although expandRow is called.
