### ISSUE TITLE
Expand only on pressing accessory view

### ISSUE THREAD

**Issue by eshwartm** [Augustyniak/RATreeView#189]
Great library. Is there a way to expand only on pressing accessory view on the cell?

**Comment by eshwartm** [comment]
Well I guess I'll have to use delegate from table view cell class.

**Comment by av089** [comment]
@eshwartm 
how did you solve this?
I also want to use + & - buttons for expand/collapse. I want to use didselect for selection

Thank you,

**Comment by eshwartm** [comment]
@av089 
1. Make a UITableViewCell subclass for your cell. 
2. Make a protocol having a function `expandCollapseCell`. 
3. Set the delegate to the main Tree View class (let's call it TreeViewController). 
4. When the arrow/+/- button is pressed, toggle expand/collapse state in the cell 
5. Call the protocol's function `expandCollapseCell` to the main TreeViewController. 
6. In that delegate function implementation, use the library's in-built `expandRowForItem` or `collapseRowForItem`.
