### ISSUE TITLE
The separator line of previous cell disappears

### ISSUE THREAD

**Issue by sureshxaton** [Augustyniak/RATreeView#25]
The separator line of the cell above the tapped cell gets hidden.
Scenario: Tap on second cell of levelDepth 0, It open ups levelDepth1 for the same cell.
Tap again on the same cell (i.e levelDepth 0) It will close the levelDepth1 for the cell

Now observe the separator line of the previous cell. It is disappeared

**Comment by AparnaAnandan** [comment]
Hi I have the same issue but on reloading the tableview. I am using Xcode 8.0 . Please help me out for this issue.
