### ISSUE TITLE
"Control may reach end of non-void function" error on Xcode 11

### ISSUE THREAD

**Issue by sanhue0302** [Augustyniak/RATreeView#272]
File: RATreeView+Enums.m
Line: 98
+ (RATreeViewStyle)treeViewStyleForTableViewStyle:(UITableViewStyle)tableViewStyle

While project compile, this methods shows error "Control may reach end of non-void function"
Please add default return in switch case

**Comment by sanhue0302** [comment]
sorry already had a pull request

**Comment by jeffumandap22** [comment]
Hi do you got the resolution on this?

**Comment by sanhue0302** [comment]
> Hi do you got the resolution on this?

i am using this now,
pod 'RATreeView', :git => 'https://github.com/mgfjxxiexiaolong/RATreeView'

**Comment by Mina-Gerges** [comment]
Thanks @sanhue0302 . It fixes the issue.
