### ISSUE TITLE
indexPathForCell

### ISSUE THREAD

**Issue by Nonsanity** [Augustyniak/RATreeView#43]
The view should probably have indexPathForCell and/or itemForCell added to it. This would make it easier to get the associated item on a touch event, say from a button added to the cell. And there are many times when an item is available and a cell is needed.

**Comment by Augustyniak** [comment]
As of version `1.0.2` method `itemForCell:` can be used to get item associated with specific cell.

Closing. Feel free to reopen if necessary.
