### ISSUE TITLE
separatorInset crashes on iOS6

### ISSUE THREAD

**Issue by pcecchetti** [Augustyniak/RATreeView#52]
RATreeVIew contains
- (UIEdgeInsets)separatorInset
{
  return self.tableView.separatorInset;
}

- (void)setSeparatorInset:(UIEdgeInsets)separatorInset
{
  self.tableView.separatorInset = separatorInset;
}

that crash on iOS6

**Comment by Augustyniak** [comment]
Fixed in #142.

Closing. Feel free to reopen if necessary.
