### ISSUE TITLE
丫的，你这内存泄露太严重了！

### ISSUE THREAD

**Issue by yuedong56** [Augustyniak/RATreeView#59]
我用了你的ratreeview做的cell，然后用的sdwebimage加载图片，发现滑动cell 的时候内存泄露太严重了。耽误了我的项目进度，丫的赔我钱吧！
而且滑动的时候还卡，耽误我项目进度，丫的赔我钱！

**Comment by cnzlh** [comment]
只能用2个字形容，奇葩

**Comment by beimen** [comment]
@Augustyniak , This issue was an unfriendly comment of @yuedong56 , I suggest close this issue.

**Comment by Augustyniak** [comment]
@beimen Thanks for info. Closing.
