### ISSUE TITLE
Wish if the RAtreeNodeInfo passed as arguments in treeView:numberOfChildrenOfItem

### ISSUE THREAD

**Issue by iamvignesh** [Augustyniak/RATreeView#61]
My application will know if a cell is going to show the children based on the RAtreeNodeInfo value so it will be helpful if i get that parameter too in the above datasource

**Comment by Augustyniak** [comment]
As written above `RATreeNodeInfo` is no longer available in current release. There are new methods in `RATreeView` class which should be instead.

Closing. Feel free to reopen.
