### ISSUE TITLE
Expand All

### ISSUE THREAD

**Issue by tarangpatel** [Augustyniak/RATreeView#62]
Is there a way to expand all the nested cell with one call ?

**Comment by Augustyniak** [comment]
Version 1.0.0 introduces method 'expandRowForItem:expandChildren:withRowAnimation:' which allow you to expand rows with its children recursively. I think it solves your problem.

Closing. Feel free to reopen if necessary.

**Comment by talat-baig** [comment]
@tarangpatel  With reference to @jiangyuqi 's question regarding expanding only single row at a time, Can you guide me regarding how can we achieve this in swift and with RATreeView version 2.1.2
