### ISSUE TITLE
Strange issue with indentation

### ISSUE THREAD

**Issue by dpswtf** [Augustyniak/RATreeView#66]
So, I'm not sure this is on your side (it probably is on mine), but if someone could help I'd appreciate it.

So I'm indenting rows based on their level, however at first it's really not indenting properly. Only when expanding for the second time it will indent properly.

Gif: http://gyazo.com/5a1842776fe1fdbc4ca71c9bc7286482.gif

Now, I've tried a lot of redraw methods, from reloadData (on the treeview) to setNeedsDisplay, setNeedsLayout, etc. But still, no luck.

Any help appreciated, thanks!

**Comment by Augustyniak** [comment]
Hey,

Sorry for the long response time. I need source code or more details in order to be able to help you. Are you still interested in implementing desire functionality with Auto Layout?

**Comment by dpswtf** [comment]
Hi, that's okay, but it has been indeed a long time and I no longer need it. If I recall correctly I just rolled with auto-layout disabled and it served me well.

I will close it, because as I said, I no longer need it but thanks for the library, it was very useful.
