### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by BossensM** [Augustyniak/RATreeView#67]
Is it possible to add a Pull to refresh to this table ?

**Comment by rjcristy** [comment]
Any updates?

**Comment by gtgg** [comment]
i can add a refresh control on UIScrollView. But RATreeView is base on UIView. How about expose UiTableView。It's base UIScrollView

**Comment by Augustyniak** [comment]
Hey,

Underlying *scroll view* of the `RATreeView` is exposed in the public API of the `RATreeView` starting from the version 2.0.0. Example project and [README file](https://github.com/Augustyniak/RATreeView#adding-pull-to-refresh-control) contain instructions regarding the way refresh control can be used with `RATreeView`. 

I hope that it helps.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
