### ISSUE TITLE
How to create a header on top of tree

### ISSUE THREAD

**Issue by danielbh** [Augustyniak/RATreeView#72]
Hello, 

Thanks for your awesome library. It's really easy and clean to use. I'm trying to create a view above the tree view. As a header or otherwise. I'd like this "header" view to scroll with the table. I'm having a hard time finding out how to do this in the documentation. How is this done? Any help would be much appreciated. Thank you!

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen.
