### ISSUE TITLE
scrolling hangs with more then 50 records

### ISSUE THREAD

**Issue by DmitryVaganov** [Augustyniak/RATreeView#79]
scrolling hangs with more then 50 records

**Comment by sadaqata** [comment]
Is this now merged with the same branch?

**Comment by fins** [comment]
I've created a pull request with this fix some time ago but it is still waiting for acceptance.

**Comment by vbrylinskiy** [comment]
I don't think that my workaround should be merged into the main repo. The focus should be made on fixing the architecture.

**Comment by Augustyniak** [comment]
Today version 1.0.0 was released. It should fix performance issues. There are also some additional changes (described in release notes).

I hope it will help.
Closing issue. Feel free to reopen if necessary.

**Comment by jingchunYuan** [comment]
初始化时，如何展开多有的节点啊？

**Comment by wuyezhiguhun** [comment]
Hello, I now have 50000 records, each time you expand and merge nodes are very slow, how to solve?（你好，我现在有50000条记录，每次展开和合并节点的时候都很慢，请问怎么能解决？）

**Comment by MrNAVY** [comment]
@implementation RATreeView (TableViewDataSource)

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
  return 1;
}
how can i change this method ,i want return more section?

**Comment by MrNAVY** [comment]
要展开多个section 怎么做呢？所有的页面都连着在一起，要分开一些section 好像做不到
