### ISSUE TITLE
Selecting a cell makes its top cell separator disappear.

### ISSUE THREAD

**Issue by sadaqata** [Augustyniak/RATreeView#82]

**Comment by fins** [comment]
I've noticed the same issue. However implementing following method solved the problem for me:

    - (void)treeView:(RATreeView *)treeView didSelectRowForItem:(JZBTreeObject *)item {
        [treeView deselectRowForItem:item animated:NO];
    }

**Comment by Augustyniak** [comment]
Closing as duplicate. Please move further discussion to the #28.
