### ISSUE TITLE
crash in 'cellForItem:item'

### ISSUE THREAD

**Issue by rp-snt** [Augustyniak/RATreeView#84]
I get a crash with this error:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 10 beyond bounds [0 .. 9]'

fixed it:
```objective-c
 - (UITableViewCell *)cellForItem:(id)item
 {
   NSIndexPath *indexPath = [self indexPathForItem:item];
-  return [self.tableView cellForRowAtIndexPath:indexPath];
+  UITableViewCell *cell = nil;
+  @try {
+    cell = [self.tableView cellForRowAtIndexPath:indexPath];
+  }
+  @catch (NSException *exception) {
+    cell = nil;
+  }
+  return cell;
 }
```

**Comment by Augustyniak** [comment]
@rp-snt  I added an example project which is entirely written in Swift. It can be found at https://github.com/Augustyniak/RATreeView/tree/master/Examples. Just run example project and select RATreeViewBasicExampleSwift target to run it.

Please take a look at #83 for more details.

I hope that it helps.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
