### ISSUE TITLE
Missing above separator line when pressing current cell.

### ISSUE THREAD

**Issue by gclsoft** [Augustyniak/RATreeView#86]
When pressing notebook2, the gray separator line between notebook1 & notebook2 is missing

**Comment by jeffreality** [comment]
I worked around this by removing the separator lines:

tv.separatorColor = [UIColor clearColor];

and added a one pixel UIView of a lightgray color to the bottom of the RATableViewCell.xib

**Comment by annehiro** [comment]
Like this? 
    UIView* separatorView = [[UIView alloc]initWithFrame:CGRectMake(0, self.frame.size.height-1, self.frame.size.width, 1)];
    separatorView.backgroundColor = [UIColor lightGrayColor];
    [self addSubview:separatorView];

**Comment by Augustyniak** [comment]
Closing as duplicate. Please move further discussion to the #28.
