### ISSUE TITLE
Collapse animation problem on iOS 8

### ISSUE THREAD

**Issue by fins** [Augustyniak/RATreeView#90]
Steps to reproduce with demo project:
1. add 3 child rows to Food section
2. expand Food section
3. scroll treeview to the bottom so the last cell Walls is visible on the bottom
4. press Food to collapse this section

On iOS 8 rows below Food section will scroll to the top and at the end of animation there will be a sudden jump of cells to the bottom. On iOS 7 this problem does not seem to exist - cells on the bottom do not move and cells above the Food section will scroll to the bottom and everything will look smoothly.

**Comment by fins** [comment]
If someone also meet this problem then as a workaround it is possible to add a scroll to bottom animation quite easily like this:

    - (void)treeView:(RATreeView *)treeView didCollapseRowForItem:(id)item
    {
        treeView.treeFooterView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 1000)];
        [UIView beginAnimations:nil context:NULL];
        treeView.treeFooterView = nil;
        [UIView commitAnimations];
    }

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
