### ISSUE TITLE
where shouldItemBeExpandedAfterDataReload?

### ISSUE THREAD

**Issue by LvJianfeng** [Augustyniak/RATreeView#97]

**Comment by Augustyniak** [comment]
This method was removed in 1.0 version of the `RATreeView`. 

Closing. Feel free to repoen if necessary.

**Comment by LvJianfeng** [comment]
Thank you!

**Comment by Zwergal** [comment]
What is the new way to get this feature back? I just updated, but I need to expand the items when I reload the data.

**Comment by ehabyasser** [comment]
@Zwergal did you solve this problem also I want to expand the items when I reload the data.

**Comment by Zwergal** [comment]
@ehabyasser Phew, this was a while back :)
But yes, I solved this issue.

After reloading the data I call a custom method where I expand all items manually.
To do that you have to store the parents for every node, so you can then expand the item and all its parents.

Something like this:
```
...  
[self.treeViewMenu reloadData];
[self expandCellsToSelectedCell];
...

-(void) expandCellsToSelectedCell {
    NSArray *allParentsToExpand = [self getAllParentNodesFrom:lastSelectedNode];
    for (int i = 0; i < allParentsToExpand.count; i++) {
      Node *node = (Node*)[allParentsToExpand objectAtIndex:i];
      [self.treeViewMenu expandRowForItem:((Node*)[allParentsToExpand objectAtIndex:i]) expandChildren:NO withRowAnimation:RATreeViewRowAnimationNone];
      ExpandableCell * cell = (ExpandableCell*)[self.treeViewMenu cellForItem:node];
      cell.expandButton.selected = YES;
  }
}

```

This is not the full code but I hope you get the idea.
